version: "3"

services:
  api:
    image: linkextractor-api:step6-ruby-nc
    build: ./api
    ports:
      - "4567:4567"
    volumes:
      - ./logs:/app/logs
  web:
    image: linkextractor-web:step6-php
    build: ./www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:4567/api/
